app:
  port: "8080"
  logfile: "/data/log-go/server-log"
#uri:
  #UriName1: "clinetrespones"
  #  logpath1: "/opt/logs/app/clinetrespones"
  #UriName: "clinetspeed"
  #  logpath: "/opt/logs/app/clinetspeed"
