app:
  port: "8080"
  logpath: "/data/log-go"
  logfile: "server.log"
  ukey: "fa628786e20df8228570f0eae6f9bc99"
  vtoken: "ohSh8Ohyieg1shaim852uw"
  salt: "beif@ie8Vo9UPah"
redis:
  port: "6379"
  auth: "MDNcVb924a"
  ip: "172.16.99.200"
  # redis TTL  sec
  ttl: 3000
url1:
  logname: "clinetspeed.log"