app:
  port: "8080"
  logpath: "/data/log-go"
  logfile: "server.log"
#uri:
  #UriName1: "clinetrespones"
  #  logpath1: "/opt/logs/app/clinetrespones"
  #UriName: "clinetspeed"
  #  logpath: "/opt/logs/app/clinetspeed"
url1:
  logname: "clinetspeed.log"