app:
  port: "8080"
  logpath: "/data/log-go"
  logfile: "server.log"
  ukey: "fa628786e20df8228570f0eae6f9bc99"
  salt: "beif@ie8Vo9UPah"
#uri:
  #UriName1: "clinetrespones"
  #  logpath1: "/opt/logs/app/clinetrespones"
  #UriName: "clinetspeed"
  #  logpath: "/opt/logs/app/clinetspeed"
redis:
  port: "6379"
  auth: "MDNcVb924a"
  ip: "127.0.0.1"
  ttl: 300

url1:
  logname: "clinetspeed.log"